
            @256
            D=A
            @SP
            M=D
            
            @Sys.init$ret.0
            D=A
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @LCL
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @ARG
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THIS
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THAT
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @SP
            D=M
            @5
            D=D-A
            @0
            D=D-A
            @ARG
            M=D
            @SP
            D=M
            @LCL
            M=D
            @Sys.init
            0;JMP
            (Sys.init$ret.0)
            
            (Main.fibonacci)
            
                    @ARG
                    D=M
                    @0
                    A=D+A
                    D=M
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @2
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_1
                D;JLT
                @SP
                A=M
                M=0
                @end_1
                0;JMP
                (Jmp_1)
                @SP
                A=M
                M=-1
                (end_1)
                @SP
                M=M+1
                
            @SP
            M=M-1
            A=M
            D=M
            @N_LT_2
            D;JNE
            
            @N_GE_2
            0;JMP
            
            (N_LT_2)
            
                    @ARG
                    D=M
                    @0
                    A=D+A
                    D=M
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
            @LCL
            D=M
            @13
            M=D
            @5
            A=D-A
            D=M
            @14
            M=D
            @SP
            M=M-1
            A=M
            D=M
            @ARG
            A=M
            M=D
            D=A
            @SP
            M=D+1
            @13
            D=M
            @1
            A=D-A
            D=M
            @THAT
            M=D
            @13
            D=M
            @2
            A=D-A
            D=M
            @THIS
            M=D
            @13
            D=M
            @3
            A=D-A
            D=M
            @ARG
            M=D 
            @13
            D=M
            @4
            A=D-A
            D=M
            @LCL
            M=D
            @14
            A=M
            0;JMP
            
            (N_GE_2)
            
                    @ARG
                    D=M
                    @0
                    A=D+A
                    D=M
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @2
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=M-D
                @SP
                M=M+1
            @Main.fibonacci$ret.2
            D=A
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @LCL
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @ARG
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THIS
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THAT
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @SP
            D=M
            @5
            D=D-A
            @1
            D=D-A
            @ARG
            M=D
            @SP
            D=M
            @LCL
            M=D
            @Main.fibonacci
            0;JMP
            (Main.fibonacci$ret.2)
            
                    @ARG
                    D=M
                    @0
                    A=D+A
                    D=M
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @1
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=M-D
                @SP
                M=M+1
            @Main.fibonacci$ret.3
            D=A
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @LCL
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @ARG
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THIS
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THAT
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @SP
            D=M
            @5
            D=D-A
            @1
            D=D-A
            @ARG
            M=D
            @SP
            D=M
            @LCL
            M=D
            @Main.fibonacci
            0;JMP
            (Main.fibonacci$ret.3)
            
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=D+M
                @SP
                M=M+1
                
            @LCL
            D=M
            @13
            M=D
            @5
            A=D-A
            D=M
            @14
            M=D
            @SP
            M=M-1
            A=M
            D=M
            @ARG
            A=M
            M=D
            D=A
            @SP
            M=D+1
            @13
            D=M
            @1
            A=D-A
            D=M
            @THAT
            M=D
            @13
            D=M
            @2
            A=D-A
            D=M
            @THIS
            M=D
            @13
            D=M
            @3
            A=D-A
            D=M
            @ARG
            M=D 
            @13
            D=M
            @4
            A=D-A
            D=M
            @LCL
            M=D
            @14
            A=M
            0;JMP
            
            (Sys.init)
            
                    @4
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
            @Main.fibonacci$ret.4
            D=A
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @LCL
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @ARG
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THIS
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THAT
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @SP
            D=M
            @5
            D=D-A
            @1
            D=D-A
            @ARG
            M=D
            @SP
            D=M
            @LCL
            M=D
            @Main.fibonacci
            0;JMP
            (Main.fibonacci$ret.4)
            
            (END)
            
            @END
            0;JMP
            