
            @256
            D=A
            @SP
            M=D
            
            @Sys.init$ret.i0
            D=A
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @LCL
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @ARG
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THIS
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @THAT
            D=M
            @SP
            A=M
            M=D
            @SP
            M=M+1
            @SP
            D=M-5-0
            @ARG
            M=D
            @SP
            D=M
            @LCL
            M=D
            @Sys.init
            0;JMP
            (Sys.init$ret0)
            
            (SimpleFunction.test)
            
                @SP
                A=M
                M=0
                @SP
                M=M+1
                
                @SP
                A=M
                M=0
                @SP
                M=M+1
                
                    @LCL
                    D=M
                    @0
                    A=D+A
                    D=M
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @LCL
                    D=M
                    @1
                    A=D+A
                    D=M
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=D+M
                @SP
                M=M+1
                
                @SP
                M=M-1
                A=M
                M=!M
                @SP
                M=M+1
                
                    @ARG
                    D=M
                    @0
                    A=D+A
                    D=M
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=D+M
                @SP
                M=M+1
                
                    @ARG
                    D=M
                    @1
                    A=D+A
                    D=M
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=M-D
                @SP
                M=M+1
            @LCL
            D=M
            @13
            M=D
            @5
            A=D-A
            D=M
            @14
            M=D
            @SP
            M=M-1
            A=M
            D=M
            @ARG
            A=M
            M=D
            D=A
            @SP
            M=D+1
            @13
            D=M
            @1
            A=D-A
            D=M
            @THAT
            M=D
            @13
            D=M
            @2
            A=D-A
            D=M
            @THIS
            M=D
            @13
            D=M
            @3
            A=D-A
            D=M
            @ARG
            M=D 
            @13
            D=M
            @4
            A=D-A
            D=M
            @LCL
            M=D
            @14
            A=M
            0;JMP
            