
                    @17
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @17
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_0
                D;JEQ
                @SP
                A=M
                M=0
                @end_0
                0;JMP
                (Jmp_0)
                @SP
                A=M
                M=-1
                (end_0)
                @SP
                M=M+1
                
                    @17
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @16
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_1
                D;JEQ
                @SP
                A=M
                M=0
                @end_1
                0;JMP
                (Jmp_1)
                @SP
                A=M
                M=-1
                (end_1)
                @SP
                M=M+1
                
                    @16
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @17
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_2
                D;JEQ
                @SP
                A=M
                M=0
                @end_2
                0;JMP
                (Jmp_2)
                @SP
                A=M
                M=-1
                (end_2)
                @SP
                M=M+1
                
                    @892
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @891
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_3
                D;JLT
                @SP
                A=M
                M=0
                @end_3
                0;JMP
                (Jmp_3)
                @SP
                A=M
                M=-1
                (end_3)
                @SP
                M=M+1
                
                    @891
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @892
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_4
                D;JLT
                @SP
                A=M
                M=0
                @end_4
                0;JMP
                (Jmp_4)
                @SP
                A=M
                M=-1
                (end_4)
                @SP
                M=M+1
                
                    @891
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @891
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_5
                D;JLT
                @SP
                A=M
                M=0
                @end_5
                0;JMP
                (Jmp_5)
                @SP
                A=M
                M=-1
                (end_5)
                @SP
                M=M+1
                
                    @32767
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @32766
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_6
                D;JGT
                @SP
                A=M
                M=0
                @end_6
                0;JMP
                (Jmp_6)
                @SP
                A=M
                M=-1
                (end_6)
                @SP
                M=M+1
                
                    @32766
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @32767
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_7
                D;JGT
                @SP
                A=M
                M=0
                @end_7
                0;JMP
                (Jmp_7)
                @SP
                A=M
                M=-1
                (end_7)
                @SP
                M=M+1
                
                    @32766
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @32766
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                D=M-D
                @Jmp_8
                D;JGT
                @SP
                A=M
                M=0
                @end_8
                0;JMP
                (Jmp_8)
                @SP
                A=M
                M=-1
                (end_8)
                @SP
                M=M+1
                
                    @57
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @31
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                    @53
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=D+M
                @SP
                M=M+1
                
                    @112
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=M-D
                @SP
                M=M+1
                @SP
                M=M-1
                A=M
                M=-M
                @SP
                M=M+1
                
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=D&M
                @SP
                M=M+1
                
                    @82
                    D=A
                    @SP
                    A=M
                    M=D
                    @SP
                    M=M+1
                    
                @SP
                M=M-1
                A=M
                D=M
                @SP
                M=M-1
                A=M
                M=D|M
                @SP
                M=M+1
                
                @SP
                M=M-1
                A=M
                M=!M
                @SP
                M=M+1
                